### ISSUE TITLE
Battle Codes Not Working without A-Com Mode

### ISSUE THREAD

**Issue by Az-Neter** [TylerWilley/flipper-f-com#11]
Firmware version is OFW 0.102.3
V-Pet is DM20

I downloaded and added all of your code files.
I've also copied the EXACT codes used in A-Com Wiki for battles, but the flipper fails to send them all every time.

I've tried 20th version and Regular battles, using codes from multiple devices, and they all say 'retry' each time.

Copymon do work fine, without fail.

Using battle over serial using the A-Com Wiki app also Does work.

It is Only trying to battle using codes sent from flipper itself which fails.

I'm using a circuit which is proven to work otherwise. My guess is a weird timing issue or code malformation? It's insanely weird that this only happens for battles and not copymon.

**Comment by TylerWilley** [comment]
Can you post the codes that consistently fail? I have a 20th I can try them on. I have had codes occasionally fail, since dmcomm is looping on both I/O and the vpet communication, sometimes the timing can cause a code to fail occasionally but a retry typically fixes the issue. I've never had a code fail consistently (except codes I've read off my devices and haven't passed through the online digirom converter before sending them)

**Comment by Az-Neter** [comment]
```
V1-2801-0001-80OE-008E-05AE-022 E-000E-000E-00OE-2B4E
```

This should be an auto win on DM20 as per A Com Wiki app. I copied the code directly from there, and it Does* work when send using A com mode.
When using just flipper, it fails every time.

**Comment by TylerWilley** [comment]
The code you posted has letter o's in it instead of zeros. When I read the same code from A-Com Wiki, it printed zeros in those places on the terminal. Additionally, I removed the space (though that may just be formatting)

After making those two changes and putting it into a flipper digirom file the code works for me:

[test.zip](https://github.com/user-attachments/files/16006633/test.zip)

**Comment by Az-Neter** [comment]
Gosh darn it. That's my stupid keyboard doing that, I have no idea why my phone acts like this.
I actually should've guessed this 🤦
It copies zeroes as Os and vice versa sometimes ...

My apologies, I probably need to go check a bunch of my other codes now too 😅
